### ISSUE TITLE
`TypeError: u.forEach is not a function`

### ISSUE THREAD

**Issue by jacobq** [indutny/self-signed#6]
I tried to use http://indutny.github.io/self-signed/ in FireFox ("Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0") but could not get anything to work. The console shows an error like `TypeError: u.forEach is not a function`. It seems to work in Google Chrome (v56) though.

**Comment by indutny** [comment]
Appears to be working on 52.0 . Is update a possibility for you? It doesn't sound to good to polyfill such JS basics as `forEach` which are practically everywhere now.

**Comment by jacobq** [comment]
Don't worry about it; just happened across it and thought I ought to file an issue in case others encounter it as well. (I'm trying to stay with the ESR channel on this particular machine so not going to manually upgrade.)

**Comment by silverwind** [comment]
`Array#forEach` is available since Firefox 1.5, must be something else.

**Comment by indutny** [comment]
This then?

```js
     u = document.querySelectorAll(".copy");
    u.forEach(function(e) {
        e.disabled = !0
    });
```

**Comment by indutny** [comment]
Anyway, it appears to be working just fine in the latest Firefox as far as I can tell.

**Comment by jacobq** [comment]
It might be something as simple as not waiting for the DOM to be ready. I don't feel like debugging it though.

**Comment by silverwind** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

Supported only since 50. I'll send you a PR.
